### ISSUE TITLE
The `GET_ACCOUNTS` permission is no longer needed

### ISSUE THREAD

**Issue by sandstrom** [Notificare/notificare-push-lib-cordova#2]
The `GET_ACCOUNTS` permission is no longer needed for GCM to work.

It used to be required for registration to GCM, but a recent Play Services update stopped using the Google account even on Froyo and Gingerbread. If you are registering to GCM with Play Services (i.e. With `GoogleCloudMessaging.register`), you no longer need this permission on any Android version.

If you are using the deprecated library (GCMRegistrar.register), you still need a Google Account on pre 4.0.4 version, which requires that permission.

So, it would be awesome if you could drop this from the SDK. Asking for permissions tend to affect downloads (lower conversion rates in Play Store). Also, Google recommends asking for no more permissions than necessary[1].

[1] https://developer.android.com/training/articles/security-tips.html#RequestingPermissions

**Comment by silentjohnny** [comment]
Hi @sandstrom,

Yes, this is something on the development roadmap for an upcoming release. Work has actually already been done, but there's a bit more involved than just switching to the new GCM classes. After regression testing this will be integrated in the mainstream release. Will keep you posted on this issue.

Thanks for mentioning, we surely appreciate this feedback.

Cheers

**Comment by sandstrom** [comment]
@silentjohnny Good to hear! High number of permissions tend to reduce store download rates, so shredding this one would be nice! :smile:
