### ISSUE TITLE
Android crash - java.lang.NullPointerException 

### ISSUE THREAD

**Issue by koenoe** [Notificare/notificare-push-lib-cordova#3]
Application crashes due to a null pointer exception (see screenshot below) after 'cordova run android'.

**Additional info:**
Android version: 4.3
Ionic version: 1.0.1, which runs on Cordova 5.3.3

<img width="593" alt="screen shot 2015-11-12 at 15 00 34" src="https://cloud.githubusercontent.com/assets/35213/11120418/c3ce0314-894f-11e5-8546-a5c38c15a646.png">

**Comment by silentjohnny** [comment]
Did you set the application class to re.notifica.cordova.BaseApplication in AndroidManifest?

**Comment by koenoe** [comment]
My bad! Can be closed, thanks. Although the AndroidManifest.xml is in the 'platforms' folder which should be in .gitignore. Is there a way to define this config in my config.xml?
