### ISSUE TITLE
Authentication error since update to 1.6.1

### ISSUE THREAD

**Issue by koenoe** [Notificare/notificare-push-lib-cordova#5]
Since I updated to 1.6.1 I get the following error when I try to build to Android:

<img width="701" alt="screen shot 2015-11-26 at 09 06 56" src="https://cloud.githubusercontent.com/assets/35213/11418119/2932f5c0-941d-11e5-83dd-273739724704.png">

All the correct application keys/secrets are set in 'notificareconfig.properties' as well as the GCM key.

Cordova version: 5.4.0
Installed platforms: Android 5.0.0
Android version of device: 5.1.1

**Comment by silentjohnny** [comment]
If you update the plugin, the notificareconfig.properties file is overwritten by the plugin default (empty) one. Add your keys again and you'll be good to go again.

**Comment by koenoe** [comment]
I'm well aware of this. This is the first thing I checked obviously. When I downgrade to library 1.6.0 everything is working fine.

I also removed the app, added android platform again, installed all plugins again, added my keys to the notificareconfig.properties file. Problem still exists. Like I said, as soon as I switch to library 1.6.0 everything is working fine.

**Comment by silentjohnny** [comment]
Please make sure you are editing the properties file in the correct location:

```sh
$PROJECT_DIR/platforms/android/assets/notificareconfig.properties
```
