### ISSUE TITLE
Opening a rich notification results in a fatal error (Android)

### ISSUE THREAD

**Issue by koenoe** [Notificare/notificare-push-lib-cordova#6]
When I sent a rich notification, for example one with HTML, I receive the push notification but as soon as I click on the push notification the application crashes. Do I miss a dependency or extra configuration?

<img width="1137" alt="screen shot 2015-11-26 at 11 27 59" src="https://cloud.githubusercontent.com/assets/35213/11420838/0ce23700-9431-11e5-995f-7feea063dffd.png">

Cordova version: 5.4.0
Installed platforms: Android 5.0.0
Android version of device: 5.1.1
Notificare library version: 1.6.0

**Comment by silentjohnny** [comment]
Notificare UI uses AppCompat themes. Please assign an AppCompat theme to that Activity or to your application as a whole, e.g. 

```xml
android:theme="@style/Theme.AppCompat.Light"
```
