### ISSUE TITLE
Latest SDK's

### ISSUE THREAD

**Issue by ispieter** [Notificare/notificare-push-lib-cordova#7]
Hello, 

We're receiving build errors with the 1.7.4 library. Updating to 1.8.5 seems to help. Is it possible to do so for this plugin?

**Comment by silentjohnny** [comment]
Hi Pieter,

There are still some 1.8.x features that have to be ported to the Cordova plugin, but I pushed a 1.8.0 release anyway (and also published to NPM). Keep in mind that this doesn't include some of the features that are in the native libraries, but everything else works as expected.

Kind regards

**Comment by ispieter** [comment]
Thank you Joris!

**Comment by ispieter** [comment]
Hi Joris,

Any word on the state of the 1.9 SDK and this plugin? We want to make our apps ready for iOS 10.

Kind regards,

Pieter

**Comment by silentjohnny** [comment]
Hi Pieter,

It's in the making, i.e., it's being tested with the iOS 1.9 SDK right now. We will release an intermediary version (1.8.2) that will include the iOS 1.9. When Android 1.9 is released, the plugin will also be upgraded to 1.9. 

Will keep you posted!

**Comment by pataar** [comment]
Thank you Joris, that would be great!
